### ISSUE TITLE
Shader Management

### ISSUE THREAD

**Issue by SomeRandomGameDev** [SomeRandomGameDev/DumbFramework#13]
Shader management is somewhat oldschool. This shall be cleaned up.

**Comment by BlockoS** [comment]
It's a little better now.
Nevertheless do we need some file describing the expected renderer states, texture modes, shaders, inputs and outputs ? Something similar to Ogre, Unity3D, whatever materials/effects?
Or let users do whatever they want in C++/script?

**Comment by SomeRandomGameDev** [comment]
DF is meant to be quick to master, faster to code, and brainless handy. Which solution fits this ?

**Comment by SomeRandomGameDev** [comment]
This is redundant with issue #35. Let's close this.
