### ISSUE TITLE
[Architecture] Wut?

### ISSUE THREAD

**Issue by BlockoS** [SomeRandomGameDev/DumbFramework#35]
Think about the whole architecture.
Do we need some kind of ResourceManager? RenderEngine? InputController?

**Comment by SomeRandomGameDev** [comment]
I'm currently working on it.

**Comment by SomeRandomGameDev** [comment]
The resource manager might be useful if done correctly. Singleton (brrr) render engine is questionable. Input controller can be removed or be an utterly optional treatment layer.

**Comment by SomeRandomGameDev** [comment]
Well .. The Dumb Core Engine was not very conclusive (moved from 0.1ms to 4ms rendering time !!).
See c5e98bb83dae76753ea76c10ca2bd64b27b39f11.
